### ISSUE TITLE
Debate pages don't seem to work

### ISSUE THREAD

**Issue by sixcorners** [Oceanhips/Destiny-Debate-Hub#4]
https://www.destinydebatehub.com/debate/id=140
This redirects to
https://www.destinydebatehub.com/YouTriedToEnterAnInvalidDebateIDEitherYouDidntEnterANumberOrPickedAValueThatDoesntExistDuckerZ

**Comment by Oceanhips** [comment]
I broken one of the lambda functions doing some testing.  It's been restored!  Thanks for the heads up
